[package]
name = "pwn_seagate_media_sync"
version = "0.1.0"
edition = "2021"

[dependencies.tokio]
version = "1"
features = [
    "macros",
    "net",
    "rt-multi-thread",
]

[dependencies.windows]
version = "0.57.0"
features = [
    "Win32_Security",
    "Win32_System_Threading",
]

